{
    'name': 'Planificador de Producción y Abastecimiento',
    'version': '19.0.8.4.0',
    'category': 'Fabricación/Fabricación',
    'summary': 'Planificación agrupada por producto: fabricar, comprar o reabastecer entre almacenes',
    'author': 'Planificador APS',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'stock', 'sale_management', 'sale_stock', 'purchase', 'purchase_stock', 'mrp', 'resource'],
    'data': [
        'security/planner_security.xml',
        'security/ir.model.access.csv',
        'data/planner_data.xml',
        'data/planner_menu_root.xml',
        'views/sale_order_views.xml',
        'views/mrp_production_views.xml',
        'views/planning_plan_views.xml',
        'views/planning_dashboard_views.xml',
        'views/planning_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mrp_advanced_planner/static/src/js/planning_dashboard.js',
            'mrp_advanced_planner/static/src/js/planning_stock_tooltip.js',
            'mrp_advanced_planner/static/src/xml/planning_dashboard.xml',
            'mrp_advanced_planner/static/src/xml/planning_stock_tooltip.xml',
            'mrp_advanced_planner/static/src/css/planning_dashboard.css',
        ],
    },
    'installable': True, 'application': True,
}
