from collections import defaultdict

from odoo import api, fields, models, _


class PlanningDashboard(models.AbstractModel):
    _name = 'mrp.planning.dashboard'
    _description = 'Panel simple de planificación de fabricación'

    @api.model
    def get_data(self, plan_id=False, company_id=False, warehouse_id=False, date_start=False, date_end=False):
        company_id = company_id or self.env.company.id
        Plan = self.env['mrp.planning.plan']
        plan_domain = [
            ('company_id', '=', company_id),
            ('state', 'in', ('calculated', 'approved')),
        ]
        if plan_id:
            plan_domain.append(('id', '=', int(plan_id)))
        if warehouse_id:
            plan_domain.append(('warehouse_id', '=', warehouse_id))
        plans = Plan.search(plan_domain, order='date_end desc, id desc', limit=30)
        plan = plans[:1]

        Production = self.env['mrp.production']
        # The production-control dashboard is ALWAYS scoped to the selected/current plan.
        # Never mix manually created MOs or MOs generated by another planning run.
        mo_domain = [('company_id', '=', company_id), ('state', '!=', 'cancel')]
        active_warehouse = plan.warehouse_id if plan else (warehouse_id and self.env['stock.warehouse'].browse(warehouse_id))
        if plan:
            mo_domain.append(('advanced_plan_id', '=', plan.id))
        else:
            # No plan means no production-control data. This intentionally prevents
            # a global MRP dashboard from leaking unrelated manufacturing orders.
            mo_domain.append(('id', '=', 0))
        if active_warehouse and active_warehouse.manu_type_id:
            mo_domain.append(('picking_type_id', '=', active_warehouse.manu_type_id.id))
        productions = Production.search(mo_domain)

        state_labels = dict(Production._fields['state'].selection)
        preferred_order = ['draft', 'confirmed', 'progress', 'to_close', 'done']
        state_data = defaultdict(lambda: {'count': 0, 'qty': 0.0, 'remaining_qty': 0.0})
        for mo in productions:
            qty, produced = self._mo_quantities_in_product_uom(mo)
            remaining = max(qty - produced, 0.0) if mo.state != 'done' else 0.0
            state_data[mo.state]['count'] += 1
            state_data[mo.state]['qty'] += qty
            state_data[mo.state]['remaining_qty'] += remaining

        states = []
        seen = set()
        for state in preferred_order + list(state_data):
            if state in seen or state not in state_data:
                continue
            seen.add(state)
            row = state_data[state]
            states.append({
                'key': state,
                'label': state_labels.get(state, state),
                'count': row['count'],
                'qty': round(row['qty'], 2),
                'remaining_qty': round(row['remaining_qty'], 2),
            })

        lines = plan.line_ids if plan else self.env['mrp.planning.plan.line']
        forecast_lines = lines.filtered(lambda line: line.planned_production_qty > 0)
        forecast_products = []
        for line in forecast_lines.sorted(key=lambda line: (line.date_required or line.plan_id.date_end, line.sale_order_id.name or '', line.id)):
            forecast_products.append({
                'id': line.id,
                'product_id': line.product_id.id,
                'product': line.product_id.display_name,
                'sale_order': line.sale_order_id.name or '',
                'customer': line.partner_id.display_name or '',
                'delivery_date': fields.Datetime.to_string(line.date_required) if line.date_required else '',
                'sales_qty': round(line.sales_qty, 2),
                'stock_qty': round(line.stock_qty, 2),
                'manufacturing_qty': round(line.production_qty, 2),
                'suggested_qty': round(line.net_requirement_qty, 2),
                'to_produce_qty': round(line.planned_production_qty, 2),
                'uom': line.product_uom_id.name,
                'blocked': bool(line.planned_production_qty and not line.bom_id),
            })

        today = fields.Datetime.now()
        late_domain = list(mo_domain) + [('state', 'not in', ('done', 'cancel'))]
        if 'date_deadline' in Production._fields:
            late_domain.append(('date_deadline', '<', today))
            late_count = Production.search_count(late_domain)
        else:
            late_count = 0
        done_count = Production.search_count(list(mo_domain) + [('state', '=', 'done')])
        without_bom_count = len(forecast_lines.filtered(lambda line: not line.bom_id))
        open_mo_count = sum(row['count'] for row in states if row['key'] not in ('done', 'cancel'))

        # Latest/current manufacturing orders. They are intentionally based on real MRP records,
        # not planner snapshots, so the dashboard always reflects shop-floor status.
        dashboard_mos = Production.search(
            list(mo_domain),
            order='state asc, date_start desc, id desc',
            limit=30,
        )
        manufacturing_orders = [self._serialize_mo(mo, state_labels) for mo in dashboard_mos]

        # Work centers are derived ONLY from work orders belonging to this plan.
        # A work center with unrelated production must not appear here.
        Workorder = self.env['mrp.workorder']
        plan_wo_domain = [
            ('production_id.advanced_plan_id', '=', plan.id if plan else 0),
            ('production_id.state', '!=', 'cancel'),
        ]
        plan_workorders = Workorder.search(plan_wo_domain)
        workcenters = plan_workorders.mapped('workcenter_id').sorted(key=lambda wc: (wc.sequence, wc.id))
        workcenter_data = self._serialize_workcenters(workcenters, active_warehouse, plan=plan)

        return {
            'plan': plan and {
                'id': plan.id,
                'name': plan.name,
                'state': plan.state,
                'date_end': plan.date_end,
                'warehouse': plan.warehouse_id.display_name,
            } or False,
            'plans': [
                {'id': row.id, 'name': row.name, 'state': row.state, 'date_end': row.date_end}
                for row in plans
            ],
            'kpis': {
                'pending_sales_qty': round(plan.total_sales_qty, 2) if plan else 0.0,
                'stock_qty': round(plan.total_stock_qty, 2) if plan else 0.0,
                'manufacturing_qty': round(plan.total_open_mo_qty, 2) if plan else 0.0,
                'to_produce_qty': round(plan.total_to_manufacture_qty, 2) if plan else 0.0,
                'open_mo_count': open_mo_count,
                'products_to_produce': len(set(forecast_lines.mapped('product_id').ids)),
                'lines_to_produce': len(forecast_lines),
                'workcenters_running': len([wc for wc in workcenter_data if wc['running_count']]),
                'workcenters_total': len(workcenter_data),
            },
            'alerts': {
                'late_mo_count': late_count,
                'without_bom_count': without_bom_count,
                'done_mo_count': done_count,
            },
            'states': states,
            'forecast_products': forecast_products,
            'manufacturing_orders': manufacturing_orders,
            'workcenters': workcenter_data,
        }

    def _mo_quantities_in_product_uom(self, mo):
        qty = mo.product_qty or 0.0
        produced = getattr(mo, 'qty_produced', 0.0) or 0.0
        if mo.product_uom_id and mo.product_id.uom_id and mo.product_uom_id != mo.product_id.uom_id:
            qty = mo.product_uom_id._compute_quantity(qty, mo.product_id.uom_id)
            produced = mo.product_uom_id._compute_quantity(produced, mo.product_id.uom_id)
        return qty, produced

    def _serialize_mo(self, mo, state_labels=None):
        state_labels = state_labels or dict(self.env['mrp.production']._fields['state'].selection)
        qty = mo.product_qty or 0.0
        produced = getattr(mo, 'qty_produced', 0.0) or 0.0
        progress = min(round((produced / qty) * 100, 1), 100.0) if qty else (100.0 if mo.state == 'done' else 0.0)
        sale_line = mo.planning_sale_line_id
        return {
            'id': mo.id,
            'name': mo.name,
            'product': mo.product_id.display_name,
            'product_id': mo.product_id.id,
            'qty': round(qty, 2),
            'produced': round(produced, 2),
            'remaining': round(max(qty - produced, 0.0), 2),
            'uom': mo.product_uom_id.name or '',
            'state': mo.state,
            'state_label': state_labels.get(mo.state, mo.state),
            'progress': progress,
            'date_start': fields.Datetime.to_string(mo.date_start) if mo.date_start else '',
            'date_finished': fields.Datetime.to_string(mo.date_finished) if mo.date_finished else '',
            'date_deadline': fields.Datetime.to_string(mo.date_deadline) if mo.date_deadline else '',
            'plan_id': mo.advanced_plan_id.id if mo.advanced_plan_id else False,
            'plan': mo.advanced_plan_id.display_name if mo.advanced_plan_id else '',
            'sale_order': sale_line.order_id.name if sale_line else (mo.origin or ''),
        }

    def _serialize_workcenters(self, workcenters, warehouse=False, plan=False):
        Workorder = self.env['mrp.workorder']
        wo_domain = [
            ('workcenter_id', 'in', workcenters.ids),
            ('state', 'in', ('blocked', 'ready', 'progress')),
            ('production_id.state', 'not in', ('done', 'cancel')),
        ]
        if plan:
            wo_domain.append(('production_id.advanced_plan_id', '=', plan.id))
        else:
            wo_domain.append(('id', '=', 0))
        if warehouse and warehouse.manu_type_id:
            wo_domain.append(('production_id.picking_type_id', '=', warehouse.manu_type_id.id))
        workorders = Workorder.search(wo_domain, order='workcenter_id, state desc, date_start, sequence, id')
        grouped = defaultdict(lambda: self.env['mrp.workorder'])
        for wo in workorders:
            grouped[wo.workcenter_id.id] |= wo

        workcenter_state_labels = dict(self.env['mrp.workcenter']._fields['working_state'].selection)
        wo_state_labels = dict(Workorder._fields['state'].selection)
        result = []
        for wc in workcenters:
            wc_orders = grouped[wc.id]
            running = wc_orders.filtered(lambda wo: wo.state == 'progress')
            queued = wc_orders.filtered(lambda wo: wo.state in ('ready', 'blocked'))
            visible_orders = (running | queued)[:5]
            current = running[:1]
            result.append({
                'id': wc.id,
                'name': wc.display_name,
                'working_state': wc.working_state,
                'working_state_label': workcenter_state_labels.get(wc.working_state, wc.working_state),
                'running_count': len(running),
                'queue_count': len(queued),
                'oee': round(wc.oee or 0.0, 1),
                'performance': round(wc.performance or 0.0, 1),
                'current_product': current.product_id.display_name if current else '',
                'current_mo': current.production_id.name if current else '',
                'current_operation': current.name if current else '',
                'current_progress': round(current.progress or 0.0, 1) if current else 0.0,
                'orders': [{
                    'id': wo.id,
                    'mo_id': wo.production_id.id,
                    'mo': wo.production_id.name,
                    'product': wo.product_id.display_name,
                    'operation': wo.name,
                    'state': wo.state,
                    'state_label': wo_state_labels.get(wo.state, wo.state),
                    'progress': round(wo.progress or 0.0, 1),
                    'qty_produced': round(wo.qty_produced or 0.0, 2),
                    'qty_total': round(wo.qty_production or 0.0, 2),
                    'date_start': fields.Datetime.to_string(wo.date_start) if wo.date_start else '',
                    'date_finished': fields.Datetime.to_string(wo.date_finished) if wo.date_finished else '',
                    'plan': wo.production_id.advanced_plan_id.display_name if wo.production_id.advanced_plan_id else '',
                } for wo in visible_orders],
            })
        return result

    @api.model
    def action_open_mos(self, state=False, plan_id=False):
        domain = [('company_id', '=', self.env.company.id), ('state', '!=', 'cancel')]
        if plan_id:
            domain.append(('advanced_plan_id', '=', int(plan_id)))
        else:
            domain.append(('id', '=', 0))
        if state:
            domain.append(('state', '=', state))
        return {
            'type': 'ir.actions.act_window',
            'name': _('Órdenes de fabricación'),
            'res_model': 'mrp.production',
            'view_mode': 'list,form',
            'views': [(False, 'list'), (False, 'form')],
            'domain': domain,
        }

    @api.model
    def action_open_mo(self, production_id):
        mo = self.env['mrp.production'].browse(int(production_id)).exists()
        if not mo:
            return False
        return {
            'type': 'ir.actions.act_window',
            'name': _('Orden de fabricación'),
            'res_model': 'mrp.production',
            'view_mode': 'form',
            'views': [(False, 'form')],
            'res_id': mo.id,
            'target': 'current',
        }

    @api.model
    def action_open_workcenter(self, workcenter_id):
        workcenter = self.env['mrp.workcenter'].browse(int(workcenter_id)).exists()
        if not workcenter:
            return False
        return {
            'type': 'ir.actions.act_window',
            'name': _('Centro de trabajo'),
            'res_model': 'mrp.workcenter',
            'view_mode': 'form',
            'views': [(False, 'form')],
            'res_id': workcenter.id,
            'target': 'current',
        }

    @api.model
    def action_open_workorders(self, workcenter_id=False, plan_id=False):
        domain = [('company_id', '=', self.env.company.id), ('state', 'not in', ('done', 'cancel'))]
        if plan_id:
            domain.append(('production_id.advanced_plan_id', '=', int(plan_id)))
        else:
            domain.append(('id', '=', 0))
        if workcenter_id:
            domain.append(('workcenter_id', '=', int(workcenter_id)))
        return {
            'type': 'ir.actions.act_window',
            'name': _('Órdenes de trabajo'),
            'res_model': 'mrp.workorder',
            'view_mode': 'list,form',
            'views': [(False, 'list'), (False, 'form')],
            'domain': domain,
        }

    @api.model
    def action_open_late_mos(self, plan_id=False):
        domain = [
            ('company_id', '=', self.env.company.id),
            ('state', 'not in', ('done', 'cancel')),
        ]
        if plan_id:
            domain.append(('advanced_plan_id', '=', int(plan_id)))
        else:
            domain.append(('id', '=', 0))
        Production = self.env['mrp.production']
        if 'date_deadline' in Production._fields:
            domain.append(('date_deadline', '<', fields.Datetime.now()))
        return {
            'type': 'ir.actions.act_window',
            'name': _('Órdenes de fabricación atrasadas'),
            'res_model': 'mrp.production',
            'view_mode': 'list,form',
            'views': [(False, 'list'), (False, 'form')],
            'domain': domain,
        }

    @api.model
    def action_open_plan(self, plan_id):
        plan = self.env['mrp.planning.plan'].browse(int(plan_id)).exists()
        if not plan:
            return False
        return {
            'type': 'ir.actions.act_window',
            'name': _('Planificación de producción'),
            'res_model': 'mrp.planning.plan',
            'view_mode': 'form',
            'views': [(False, 'form')],
            'res_id': plan.id,
            'target': 'current',
        }
