{
    "name": "Conteo de Inventario Multiusuario - Móvil/PDA",
    "version": "19.0.7.4.5",
    "category": "Inventario",
    "license": "OPL-1",
    "author": "Oscar Morocho",
    "maintainer": "Oscar Morocho",
    "summary": "Conteo físico multiusuario para PDA con pantalla rápida sin recargas, captura por código de barras y simulación desde celular.",
    "description": """
        Gestión completa de conteos físicos de inventario para Odoo 19.
        Incluye planificación, sesiones multiusuario, interfaz optimizada para celular/PDA,
        escaneo de ubicación, producto, lote y serie, conteo ciego, tolerancias,
        clasificación de discrepancias, reconteos, aprobaciones, auditoría y ajustes de inventario.
    """,
    "images": ["static/description/banner.png"],
    "depends": ["stock_account", "purchase"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/base_setup_data.xml",
        "data/ir_cron.xml",
        "data/mail_template_data.xml",
        "views/setu_stock_inventory_count_views.xml",
        "views/setu_stock_inventory_count_planner_views.xml",
        "views/setu_inventory_count_session_views.xml",
        "views/setu_inventory_session_details_views.xml",
        "views/setu_stock_inventory_views.xml",
        "views/inventory_count_enhancement_views.xml",
        "views/pda_counting_views.xml",
        "views/stock_location_views.xml",
        "views/stock_move_views.xml",
        "views/stock_move_line_views.xml",
        "views/res_config_settings_views.xml",
        "views/actions.xml",
        "views/inventory_dashboard_views.xml",
        "wizard_views/setu_inventory_session_creator_views.xml",
        "wizard_views/setu_inventory_session_validate_wizard_views.xml",
        "wizard_views/setu_inventory_warning_message_wizard_views.xml",
        "wizard_views/setu_extra_lot_found_wizard_views.xml",
        "report_views/setu_inventory_count_report_views.xml",
        "report_views/setu_inventory_adjustment_report_views.xml",
        "report_views/setu_inventory_session_user_report_views.xml",
        "report_views/setu_count_wise_discrepancy_report_views.xml",
        "report_views/setu_product_wise_discrepancy_report_views.xml",
        "report_views/setu_location_wise_discrepancy_report_views.xml",
        "report_views/setu_inventory_session_performance_report_views.xml",
        "views/ux_kanban_views.xml",
        "data/inventory_count_snapshot_backfill.xml",
        "data/warehouse_count_lock_backfill.xml",
        "views/inventory_count_snapshot_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "setu_inventory_count_management/static/src/css/barcode.scss",
            "setu_inventory_count_management/static/src/css/inventory_count_cockpit.scss",
            "setu_inventory_count_management/static/src/js/pda_fast_count.js",
            "setu_inventory_count_management/static/src/xml/pda_fast_count.xml",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
}
